### PR TITLE
sedport now 'ok'

### PR DESCRIPTION
**Pull request by MikeFultonDev**
a good number of tests now passing
@IgorTodorovskiIBM please add this to the jenkins CI/CD process (and accept your invitation)

### CODE REVIEW

**Comment by MikeFultonDev** [comment]
NOTE: other pull requests for wget et al. have to be successful before this one can be processed.

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Comment by IgorTodorovskiIBM** [comment]
Added it here: https://128.168.139.253:8443/job/sed/

**Review by IgorTodorovskiIBM — APPROVED** [review]

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Review by IgorTodorovskiIBM — APPROVED** [review]

**Pull request merged**
